#=============================================================================================
# BOB 工程信息配置
#=============================================================================================
bob:
  application:
    systemId: BOB-LEARN
#=============================================================================================
# web端口配置
#=============================================================================================
server:
  port: 8090
#=============================================================================================
# profiles配置
#=============================================================================================
spring:
  profiles:
    active: dev
#=============================================================================================
# 健康检查，监控信息配置
#=============================================================================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
#=============================================================================================
# MyBatis信息配置
#=============================================================================================
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true